// Portfolio data modeled from exported Notion content.
window.PROJECTS = [
  {
    slug: 'pantry-pal',
    title: 'Pantry Pal',
    kind: 'uiux',
    kindLabel: 'ui/ux',
    year: '2024',
    role: 'UI Designer, UX Researcher',
    excerpt:
      'Mobile app concept tackling food waste by simplifying pantry management and meal planning.',
    tags: ['figma', 'foodtech', 'mobile'],
    href: 'case-studies/project.html?slug=pantry-pal',
    thumbLabel: 'pantry pal',
    thumb: 'public/design-assets/project-media/pantry-pal/Screenshot_2025-02-09_at_10.29.48.png',
  },
  {
    slug: 'telegram-bot-heymax',
    title: 'Telegram Bot for Trip Planning',
    kind: 'code',
    kindLabel: 'code',
    roleKind: 'growing',
    roleCategory: 'growing 🪴',
    year: '2025',
    role: 'Software Developer',
    excerpt:
      'Trip-planning Telegram bot project built for NUS Fintech Society in collaboration with HeyMax.',
    tags: ['telegram', 'automation', 'fintech'],
    href: 'case-studies/telegram-bot-heymax.html',
    showOnHome: true,
    showOnPortfolio: true,
    hideFromArchive: true,
    thumbLabel: 'image placeholder',
    thumb: '',
  },
  {
    slug: 'nusmart-dining-revamp',
    title: 'NUSMart Dining Revamp',
    kind: 'uiux',
    kindLabel: 'ui/ux',
    year: '2024',
    role: 'UI Designer, UX Researcher',
    excerpt: 'Revamped mobile app experience for NUSMart Dining.',
    tags: ['miro', 'mobile', 'service design'],
    href: 'case-studies/project.html?slug=nusmart-dining-revamp',
    thumb: 'public/design-assets/project-media/nusmart-dining-revamp/Screenshot_2025-02-09_at_10.16.15.png',
  },
  {
    slug: 'flexijio',
    title: 'FlexiJio',
    kind: 'uiux',
    kindLabel: 'ui/ux',
    year: '2024',
    role: 'UX Researcher, UI Designer',
    excerpt: 'Desktop video conferencing platform for fitness classes and remote coaching.',
    tags: ['ux research', 'desktop', 'fitness'],
    href: 'case-studies/project.html?slug=flexijio',
    thumb: 'public/design-assets/project-media/flexijio/Screenshot_2025-02-09_at_10.44.39.png',
  },
  {
    slug: 'fusion-scanner',
    title: 'Fusion Scanner',
    kind: 'uiux',
    kindLabel: 'ui/ux',
    year: '2023',
    role: 'UX Researcher, UI Designer',
    excerpt:
      'Browser extension concept to improve reading accessibility for language barriers and reading disabilities.',
    tags: ['balsamiq', 'figma', 'accessibility'],
    href: 'case-studies/fusion-scanner.html',
    thumb: 'public/design-assets/project-media/fusion-scanner/Screenshot_2025-02-08_at_11.47.11.png',
  },
  {
    slug: 'stoma-siting-cs4240',
    title: 'Stoma Siting',
    kind: 'uiux',
    kindLabel: 'research',
    hideKindTag: true,
    year: '2024',
    role: 'Researcher (Group survey, CS4240)',
    roleCategory: 'AR/VR',
    roleKind: 'role-research',
    excerpt:
      'Survey report on how AR and VR simulations can support stoma siting education and clinical preparation (CS4240, NUS).',
    tags: ['ar/vr', 'healthcare', 'survey'],
    href: 'case-studies/stoma-siting-cs4240.html',
    showOnPortfolio: true,
    hideFromArchive: true,
    thumbLabel: 'image placeholder',
    thumb: '',
  },
  {
    slug: 'magic-of-resilience',
    title: 'Magic of Resilience',
    kind: 'code',
    kindLabel: 'video',
    focusLabel: 'Videography',
    year: '2023',
    role: 'Director of Photography',
    toolsLabel: 'Adobe Premiere Pro',
    footerRows: [{ label: 'Course', value: 'NM3230 Digital Storytelling' }],
    hideRoleTag: false,
    showOnHome: true,
    showOnPortfolio: true,
    hideFromArchive: true,
    excerpt: 'A non-fictional short documentary on Meta Illusions.',
    tags: ['videography', 'premiere pro', 'documentary'],
    href: 'case-studies/project.html?slug=magic-of-resilience',
    thumb: 'public/design-assets/project-media/magic-of-resilience/magic-of-resilience-cover.png',
  },
  {
    slug: 'lions-befrienders-communications-plan',
    title: 'Integrated Communications Plan for Lions Befrienders',
    kind: 'uiux',
    kindLabel: 'strategy',
    year: '2026',
    role: 'Communication Designer',
    excerpt:
      'Strategic communications plan for volunteer, donor, and public audiences — channel mix, messaging architecture, and measurement.',
    tags: ['communications', 'non-profit', 'strategy'],
    href: 'case-studies/lions-befrienders-communications-plan.html',
    thumbLabel: 'image placeholder',
    thumb: '',
  },
  {
    slug: 'homework-1-interactive-timeline',
    title: '4-gram language model',
    kind: 'code',
    kindLabel: 'code',
    year: '2026',
    role: 'Student',
    roleCategory: 'information retrieval',
    roleKind: 'role-research',
    excerpt:
      'A language detector that predicts whether text is Malaysian, Indonesian, or Tamil.',
    tags: ['code', 'information retrieval', 'nlp', 'python'],
    href: 'case-studies/4-gram-language-model.html',
    status: 'grown',
    statusDate: '2026',
    showOnHome: true,
    showOnPortfolio: true,
    hideFromArchive: true,
    hideThumb: true,
    thumbLabel: '4-gram language model',
    thumb: '',
  },
  {
    slug: 'clinicconnect-cs2103',
    title: 'ClinicConnect',
    kind: 'code',
    kindLabel: 'desktop app',
    year: '2026',
    role: 'Software Developer',
    excerpt:
      'CS2103 ClinicConnect desktop app artifact showcase with downloadable JAR and embedded user/developer guides.',
    tags: ['java', 'desktop', 'software engineering'],
    href: 'case-studies/clinicconnect.html',
    showOnHome: true,
    showOnPortfolio: true,
    hideFromArchive: true,
    thumbLabel: 'clinicconnect app screenshot',
    thumb: 'public/design-assets/project-media/clinicconnect/clinicconnect-card-cover.png',
  },
  {
    slug: 'ziq-ip-cs2103',
    title: 'Ziq',
    kind: 'code',
    kindLabel: 'code',
    year: '2026',
    role: 'Software Developer',
    excerpt:
      'A task chatbot built using JavaFX and Gradle, demonstrated through an in-built simulator.',
    tags: ['java', 'chatbot', 'software engineering'],
    href: 'case-studies/ziq-chatbot.html',
    showOnHome: true,
    showOnPortfolio: true,
    hideFromArchive: true,
    thumbLabel: 'ziq task chatbot',
    thumb: 'public/design-assets/project-media/ziq/ziq-chatbot-cover.png',
  },
];

window.PROJECTS_NEW_VERSIONS = [
  {
    slug: 'pantry-pal-new-version',
    title: 'Pantry Pal',
    kind: 'uiux',
    kindLabel: 'ui/ux',
    year: '2024',
    role: 'UI Designer, UX Researcher',
    excerpt: 'Mobile Application designed to tackle Food Waste by simplifying pantry management and meal planning.',
    tags: ['figma', 'foodtech', 'mobile'],
    href: 'case-studies/pantry-pal.html',
    status: 'grown',
    thumbLabel: 'image placeholder',
    thumb: '',
  },
  {
    slug: 'telegram-bot-heymax',
    title: 'Telegram Bot for Trip Planning',
    kind: 'code',
    kindLabel: 'code',
    year: '2025',
    role: 'Software Developer',
    excerpt:
      'A trip-planning Telegram bot with AI\u2011generated summary messages and an in\u2011built interactive map. Built with NUS Fintech Society and HeyMax.',
    tags: ['telegram', 'automation', 'fintech'],
    href: 'case-studies/telegram-bot-heymax.html',
    status: 'grown',
    hideRoleTag: false,
    showOnHome: true,
    showOnPortfolio: true,
    hideFromArchive: true,
    hideThumb: true,
    thumbLabel: 'image placeholder',
    thumb: '',
  },
  {
    slug: 'kita-communication-intervention-new-version',
    title: 'From Blind Box to Brochure, A Communication Intervention for Kita',
    kind: 'uiux',
    kindLabel: 'ui/ux',
    year: '2024',
    role: 'Designer',
    excerpt: 'Communication design case study for Kita: a blind-box-to-brochure advocacy toolkit and how it was researched, designed, and evaluated.',
    tags: ['communication', 'intervention', 'branding'],
    href: 'case-studies/kita-communication-intervention.html',
    status: 'grown',
    thumbLabel: 'image placeholder',
    thumb: '',
  },
  {
    slug: 'flexijio-case-study',
    title: 'Flexijio',
    kind: 'uiux',
    kindLabel: 'ui/ux',
    year: '2024',
    role: 'UX Researcher, UI Designer',
    excerpt:
      'Social home-workout platform — interactive case study with TL;DR and full narrative: group sessions, per-user difficulty scaling, and mixed-methods evaluation (NM3243, NUS).',
    tags: ['ux research', 'react', 'fitness'],
    href: 'projects/flexijio-case-study/dist/index.html',
    status: 'grown',
    thumbLabel: 'image placeholder',
    thumb: '',
  },
  {
    slug: 'fusion-scanner-case-study',
    title: 'FusionScanner',
    kind: 'uiux',
    kindLabel: 'ui/ux',
    year: '2023',
    role: 'Product Designer & Researcher',
    excerpt:
      'AI-powered browser extension case study with both TL;DR and full write-up focused on multilingual reading comprehension.',
    tags: ['figma', 'accessibility', 'ai ux'],
    href: 'case-studies/fusion-scanner.html',
    status: 'grown',
    thumbLabel: 'image placeholder',
    thumb: '',
  },
  {
    slug: 'stoma-siting-cs4240',
    title: 'Stoma Siting',
    kind: 'uiux',
    kindLabel: 'research',
    hideKindTag: true,
    year: '2024',
    role: 'Researcher (Group 2)',
    roleCategory: 'AR/VR',
    roleKind: 'role-research',
    excerpt:
      'CS4240 group survey on AR/VR simulations for stoma siting — full PDF with embedded reader on the case study page.',
    tags: ['ar/vr', 'healthcare', 'survey'],
    href: 'case-studies/stoma-siting-cs4240.html',
    status: 'grown',
    showOnPortfolio: true,
    hideFromArchive: true,
    thumbLabel: 'image placeholder',
    thumb: '',
  },
  {
    slug: 'nusmart-dining-case-study',
    title: 'NUSmart Dining — A Queue Without the Anxiety',
    kind: 'uiux',
    kindLabel: 'ui/ux',
    year: '2024',
    role: 'UI Designer, UX Researcher',
    excerpt:
      'Standalone case study for the NUSmart Dining mobile redesign — transparent wait times, calmer ordering, and queue anxiety reframed as a design problem.',
    tags: ['miro', 'mobile', 'service design'],
    href: 'case-studies/nusmart-dining-case-study.html',
    status: 'grown',
    thumbLabel: 'image placeholder',
    thumb: '',
  },
  {
    slug: 'niik-personal-brand-case-study',
    title: 'Brand Style Guide',
    kind: 'uiux',
    kindLabel: 'graphic',
    hideKindTag: true,
    year: '2024',
    role: 'Graphic Designer',
    excerpt:
      'My personal brand guidelines, consisting of a logo, colour palette, typography, and tangible artifacts.',
    tags: ['brand', 'identity', 'graphic design'],
    href: 'case-studies/niik-case-study.html',
    status: 'grown',
    showOnHome: true,
    showOnPortfolio: true,
    hideFromArchive: true,
    thumb: 'public/design-assets/project-media/brand-style-guide/FP__BrandStyleGuide_W4__e0958068_NiikSeah-01.png',
  },
  {
    slug: 'magic-of-resilience',
    title: 'Magic of Resilience',
    kind: 'code',
    kindLabel: 'video',
    focusLabel: 'Videography',
    year: '2023',
    role: 'Director of Photography',
    toolsLabel: 'Adobe Premiere Pro',
    hideRoleTag: true,
    excerpt: 'A non-fictional short documentary on Meta Illusions.',
    tags: ['videography', 'premiere pro', 'documentary'],
    href: 'case-studies/project.html?slug=magic-of-resilience',
    status: 'grown',
    showOnHome: true,
    showOnPortfolio: true,
    hideFromArchive: true,
    thumb: 'public/design-assets/project-media/magic-of-resilience/magic-of-resilience-cover.png',
  },
  {
    slug: 'lions-befrienders-communications-plan',
    title: 'Integrated Communications Plan for Lions Befrienders',
    kind: 'uiux',
    kindLabel: 'strategy',
    year: '2026',
    role: 'Communication Designer',
    excerpt:
      'Strategic communications plan for volunteer, donor, and public audiences — channel mix, messaging architecture, and measurement.',
    tags: ['communications', 'non-profit', 'strategy'],
    href: 'case-studies/lions-befrienders-communications-plan.html',
    status: 'grown',
    thumbLabel: 'image placeholder',
    thumb: '',
  },
  {
    slug: 'homework-1-interactive-timeline',
    title: '4-gram language model',
    kind: 'code',
    kindLabel: 'code',
    year: '2026',
    role: 'Student',
    roleCategory: 'information retrieval',
    roleKind: 'role-research',
    excerpt:
      'A language detector that predicts whether text is Malaysian, Indonesian, or Tamil.',
    tags: ['code', 'information retrieval', 'nlp', 'python'],
    href: 'case-studies/4-gram-language-model.html',
    status: 'grown',
    statusDate: '2026',
    showOnHome: true,
    showOnPortfolio: true,
    hideFromArchive: true,
    hideThumb: true,
    thumbLabel: '4-gram language model',
    thumb: '',
  },
  {
    slug: 'clinicconnect-cs2103',
    title: 'ClinicConnect',
    kind: 'code',
    kindLabel: 'desktop app',
    year: '2026',
    role: 'Software Developer',
    excerpt:
      'CS2103 ClinicConnect desktop app artifact showcase with downloadable JAR and embedded user/developer guides.',
    tags: ['java', 'desktop', 'software engineering'],
    href: 'case-studies/clinicconnect.html',
    status: 'grown',
    showOnHome: true,
    showOnPortfolio: true,
    hideFromArchive: true,
    thumbLabel: 'clinicconnect app screenshot',
    thumb: 'public/design-assets/project-media/clinicconnect/clinicconnect-card-cover.png',
  },
  {
    slug: 'ziq-ip-cs2103',
    title: 'Ziq',
    kind: 'code',
    kindLabel: 'code',
    year: '2026',
    role: 'Software Developer',
    excerpt:
      'A task chatbot built using JavaFX and Gradle, demonstrated through an in-built simulator.',
    tags: ['java', 'chatbot', 'software engineering'],
    href: 'case-studies/ziq-chatbot.html',
    status: 'grown',
    showOnHome: true,
    showOnPortfolio: true,
    hideFromArchive: true,
    thumbLabel: 'ziq task chatbot',
    thumb: 'public/design-assets/project-media/ziq/ziq-chatbot-cover.png',
  },
];

window.FEATURED = ['pantry-pal', 'telegram-bot-heymax', 'fusion-scanner'];

window.CASE_STUDIES = {
  'pantry-pal': {
    subtitle: 'Mobile app concept for reducing household food waste through smarter pantry workflows.',
    timeline: 'Oct-Nov 2024',
    tools: 'Figma',
    heroImage: 'public/design-assets/project-media/pantry-pal/Screenshot_2025-02-09_at_10.29.48.png',
    gallery: [
      'public/design-assets/project-media/pantry-pal/Screenshot_2025-04-09_at_09.15.11.png',
      'public/design-assets/project-media/pantry-pal/Screenshot_2025-04-09_at_09.15.42.png',
      'public/design-assets/project-media/pantry-pal/Screenshot_2025-04-09_at_09.23.09.png',
      'public/design-assets/project-media/pantry-pal/8fea386d-f56f-4252-96e0-98efbbb2fbfe.png',
      'public/design-assets/project-media/pantry-pal/39b9c882-e150-425e-8bb1-80b897ed7aed.png',
    ],
    sections: [
      {
        header: 'Background & Problem Framing',
        body: [
          'Pantry Pal is a mobile UI/UX concept designed to tackle food waste by simplifying pantry management and meal planning.',
          'The project began with a clear behavior gap: users cared about waste but still overbought and forgot existing items, which led to duplication and expiry.',
        ],
      },
      {
        header: 'Research Insights',
        bullets: [
          'Awareness of food waste did not reliably translate to daily action.',
          'Users prioritized convenience over sustainability when shopping under time pressure.',
          'Waste-reducing behaviors were perceived as tedious without strong in-app support.',
          'Participants preferred low-friction capture methods (voice, barcode scan, quick add).',
        ],
      },
      {
        header: 'Existing User Flow',
        body: [
          'The baseline grocery journey was mapped from purchase to unpacking to identify where duplication, forgotten inventory, and expiry risk occur.',
          'This revealed that most breakdowns happened before planning (during shopping decisions) and after purchase (during pantry organization).',
        ],
      },
      {
        header: 'Lo-Fi Prototype',
        body: [
          'A low-fidelity prototype was created to test core workflows: onboarding, pantry setup, grocery input, expiry tracking, and recipe/meal planning loops.',
          'The focus at this stage was information clarity and step-by-step usability rather than visual polish.',
        ],
      },
      {
        header: 'User Testing Results',
        bullets: [
          'Navigation hierarchy was validated, with Pantry positioned for faster repeated access.',
          'Grid-style visual treatment for expired items performed better than list-style alternatives.',
          'Recipe portion controls were seen as highly useful for reducing over-cooking and over-buying.',
          'Users requested stronger persistence of previously entered groceries for faster repeat actions.',
        ],
      },
      {
        header: 'Mid-Fi Prototype & Design Considerations',
        body: [
          'Mid-fidelity iterations incorporated tested navigation patterns, clearer interaction labels, and more practical pantry/meal planning flows.',
          'Color, accessibility contrast, and action naming were refined to support both first-time and repeat usage.',
        ],
      },
      {
        header: 'Outcome & Skills Developed',
        bullets: [
          'Delivered a complete prototype and validated interaction model for pantry and meal workflows.',
          'Strengthened user research, interview synthesis, empathy mapping, and interaction design execution.',
          'Produced a concept with clear potential to reduce avoidable food waste through daily behavioral nudges.',
        ],
      },
    ],
  },
  'telegram-bot-heymax': {
    subtitle: 'Built by NUS Fintech Society, in collaboration with HeyMax.',
    timeline: 'Aug 2025 - May 2026',
    tools: 'Placeholder',
    focus: 'Placeholder',
    heroImage: 'public/design-assets/project-media/telegram-bot-heymax/image.png',
    gallery: [],
    tldrSections: [
      {
        header: 'Problem',
        body: [
          'Trip planning in Telegram group chats is messy and time-consuming because users share links across multiple messages without a structured way to consolidate destinations, activities, and accommodations.',
        ],
      },
      {
        header: 'Solution',
        bullets: [
          'A Telegram bot that collects planning context through short Q&A prompts.',
          'It analyses shared links to extract destinations, activities, and accommodations.',
          'It generates a concise AI summary and links to an interactive map with pinned locations.',
        ],
      },
      {
        header: 'How Solution Works',
        bullets: [
          'Users run /plan to start context capture and link collation.',
          'Bot confirms links and allows removals via /removelink.',
          'LLM returns a summary for group chat; users can re-run with /summarise.',
          'If trip context changes, the bot restarts Q&A before generating a new summary.',
        ],
      },
    ],
    sections: [
      {
        header: 'Problem Statement',
        body: [
          'Young adults, especially university students, usually plan their overseas trips on Telegram. Telegram does not have specialised features for trip planning, leading to messy and time-consuming collaboration. There is a gap in the market and hence, desirability in enhancing travel planning processes on Telegram.',
        ],
      },
      {
        header: 'Project Scope',
        body: [
          'We aim to optimise the experience of trip planning on Telegram by providing a comprehensive summary message that contains embedded links and AI-generated short descriptions of places, accommodations and activities users send in the chat.',
        ],
      },
      {
        header: 'Key features',
        bullets: [
          'Pre-processing user query: The bot asks contextual questions to personalise and enhance the accuracy of the summary plan.',
          'Content Analysis: Utilise API calls from various platforms to detect destinations, points of interest, and themes from shared social media content. By converting raw inspiration into machine-readable data, accuracy is ensured across the workflow and thus, the output message.',
          'AI summary message generation: After data extraction of the links, AI gives a structured summary of the activities, locations and accommodations saved.',
          'Trip Overview: A clear summary of the trip, including flights, overall duration, and key timings.',
          'Activity Discovery: Consolidate social media links for recommended places to visit, each accompanied with a one-line summary.',
          'Accommodation Options: Gather and organise accommodation links, presenting them as one-line summaries with estimated costs.',
          'Visual Map: After generating a summary, a map with pins of the relevant locations saved will be linked. This gives users a visual cue of the places they are interested in, facilitating trip planning.',
        ],
      },
      {
        header: 'User Flow',
        bullets: [
          '1. Initiation of bot: Users can add the Telegram Bot at any point in time during the discussion.',
          '2. Trigger Context Q&A: User enters /start. The bot enters Pre-processing Q&A, asking short contextual questions. Answers are collected and stored as structured inputs. Users can click "🚀 Start sending links" to trigger bot to start collating links.',
          '3. Confirmation: After collating the links, users can enter /links to view links collated. The bot confirms the list of links. If users want to remove any, they can click "🗑️ Remove links", and then enter the index of the link to be removed.',
          '4. Content Analysis: The bot uses API calls on the shared links (up till the point of /plan) and parses text to detect destinations, points of interest, and themes. The bot then outputs machine-readable data.',
          '5. Summary message generation (LLM-powered): The structured inputs (Q&A + analysed content) are fed to the LLM to return a summary message.',
          '6. Output: The user can enter /plan and select "🚀 Generate summary message" for the summary message.',
          '7. Reiterations: Users can continue sending links and entering /plan. The bot will confirm if other trip details remain unchanged; if unchanged, an updated summary is generated, otherwise it restarts the Q&A before creating a new summary message.',
        ],
      },
      {
        header: 'Visual Map Implementation',
        body: [
          'Details',
        ],
        bullets: [
          '1. Telegram Bot sends the link of the map (rendered in a webpage) after the summary output.',
          '2. Clicking on the link guides the user to the webpage (either on Telegram via Mini App Feature or Web Browser).',
          '3. The map is live and interactive, allowing users to view different pinned locations and clicking on pins to view more details.',
        ],
      },
      {
        header: 'Deliverables',
        bullets: [
          '1. Map showing the pinned locations',
          '2. Pins categorised based on colour',
          '3. Users can click on the pins to obtain more information',
        ],
      },
      {
        header: 'Technical Implementation Plan',
        body: [
          'Telegram Mini App',
          'Telegram’s inbuilt UI restricts custom markers. Shifting the map into a mini-app to load markers based on the chat will be the workaround.',
          'The mini-app provides the following functionalities as well:',
        ],
        bullets: [
          '1. Multiple markers',
          '2. Custom info cards',
          '3. Custom icons',
          '4. Handle user interaction',
        ],
      },
      {
        header: 'API/ Software required',
        bullets: [
          '1. N8n team account',
          '2. Youtube API (For now, we will use on the free tier of google workspace, assuming there is one, else a minor charge would need to be paid here as well).',
          '3. Apify API (Generally makes it easier to scrape data from all kinds of different services, and can not only be used in this project, but for other projects as well. It also integrates well with different services).',
          '4. OpenAI API Tokens',
          '5. Dify (LLM manager of choice for now, has an education discount of 100% but difficult to obtain).',
        ],
      },
      {
        header: 'Steps moving forward',
        body: [
          'Design for Map: Things to consider moving forward are',
        ],
        bullets: [
          '1. Accessibility',
          '2. Dark Mode',
          '3. Emoji Customisation for Map Pins',
          '4. Tags for Map Pins',
        ],
      },
    ],
  },
  'nusmart-dining-revamp': {
    subtitle: 'Revamped mobile dining journey for NUSMart with clearer navigation and decision support.',
    timeline: 'Sep 2024',
    tools: 'Miro',
    heroImage: 'public/design-assets/project-media/nusmart-dining-revamp/Screenshot_2025-02-09_at_10.16.15.png',
    gallery: ['public/design-assets/project-media/nusmart-dining-revamp/Screenshot_2025-02-09_at_10.16.15.png'],
    sections: [
      {
        header: 'Project Overview',
        body: [
          'NUSMart Dining Revamp reimagined the mobile dining experience to make exploration, selection, and ordering more intuitive.',
        ],
      },
      {
        header: 'Research & Insight',
        body: [
          'Mapped current pain points in the dining flow and identified moments where users felt uncertainty or unnecessary friction.',
        ],
      },
      {
        header: 'Design Direction',
        bullets: [
          'Simplified navigation hierarchy for quicker menu and option discovery.',
          'Prioritized clearer information architecture to support faster user decisions.',
          'Refined interaction cues so primary actions were easier to locate at each step.',
        ],
      },
      {
        header: 'Outcome',
        body: [
          'Produced a revamped experience framework with improved usability and clearer journey continuity.',
        ],
      },
    ],
  },
  flexijio: {
    subtitle: 'Desktop video conferencing concept tailored for fitness instruction and participation.',
    timeline: 'Feb-Apr 2024',
    tools: 'Miro',
    heroImage: 'public/design-assets/project-media/flexijio/Screenshot_2025-02-09_at_10.44.39.png',
    gallery: [
      'public/design-assets/project-media/flexijio/Screenshot_2025-02-04_at_11.49.05.png',
      'public/design-assets/project-media/flexijio/Screenshot_2025-02-04_at_11.51.47.png',
      'public/design-assets/project-media/flexijio/Screenshot_2025-02-04_at_11.53.35.png',
      'public/design-assets/project-media/flexijio/Screenshot_2025-02-04_at_11.54.49.png',
      'public/design-assets/project-media/flexijio/Screenshot_2025-02-04_at_12.03.46.png',
    ],
    sections: [
      {
        header: 'Project Scope',
        body: [
          'FlexiJio is a desktop video conferencing platform concept specifically designed for fitness sessions.',
          'The solution was positioned as a complementary option for users who want social, guided workouts at home.',
        ],
      },
      {
        header: 'Disclaimer & Product Boundaries',
        body: [
          'FlexiJio is not meant to replace in-person gyms or users who prefer solo workouts.',
          'It is designed for users seeking flexible, community-supported virtual fitness experiences.',
        ],
      },
      {
        header: 'Key Discoveries',
        bullets: [
          'Users wanted virtual training to feel personal and responsive, not generic.',
          'Community and social accountability improved motivation consistency.',
          'Sustained engagement depended on personalization, customization, and integrated tracking.',
        ],
      },
      {
        header: 'Personas & Proposed Use Scenario',
        body: [
          'Personas were developed to represent real scheduling, motivation, and family/work constraints.',
          'Use-scenario mapping validated notification timing, class entry flow, and social touchpoints as key retention moments.',
        ],
      },
      {
        header: 'Prototype Direction',
        bullets: [
          'Defined workflows for class discovery, session participation, and post-session follow-through.',
          'Integrated health tracking and FAQ/help touchpoints to reduce session friction.',
          'Storyboarded multi-step feature use to align instructor and participant expectations.',
        ],
      },
      {
        header: 'Outcome',
        body: [
          'Delivered a UX concept focused on fitness-centric video interaction design and session management clarity.',
        ],
      },
    ],
  },
  'fusion-scanner': {
    subtitle: 'Accessibility-oriented browser extension concept to improve reading comprehension and comfort.',
    timeline: 'Sep-Nov 2023',
    tools: 'Balsamiq, Figma',
    heroImage: 'public/design-assets/project-media/fusion-scanner/Screenshot_2025-02-08_at_11.47.11.png',
    gallery: [
      'public/design-assets/project-media/fusion-scanner/Screenshot_2025-02-08_at_11.45.38.png',
      'public/design-assets/project-media/fusion-scanner/Screenshot_2025-02-08_at_11.47.50.png',
      'public/design-assets/project-media/fusion-scanner/Screenshot_2025-02-08_at_12.27.32.png',
      'public/design-assets/project-media/fusion-scanner/Screenshot_2025-02-08_at_20.43.27.png',
      'public/design-assets/project-media/fusion-scanner/Screenshot_2025-02-09_at_10.50.15.png',
    ],
    sections: [
      {
        header: 'Project Context',
        body: [
          'Fusion Scanner is a browser extension concept created to support users facing language barriers and reading disabilities.',
          'The work addressed comprehension friction in everyday long-form digital reading.',
        ],
      },
      {
        header: 'Limitations of Current Solutions',
        body: [
          'Existing tools either lacked structured editing/regeneration controls or omitted summarization capabilities.',
          'Users needed in-context support with clearer control over output quality and format.',
        ],
      },
      {
        header: 'Target User Groups',
        body: [
          'Primary users included non-native English readers and users with reading-comprehension constraints.',
          'Secondary users included academic professionals, tutors, and heavy digital readers who benefit from reading acceleration.',
        ],
      },
      {
        header: 'User Interviews, Affinity Diagram & Personas',
        body: [
          'Interviews with target users were synthesized into affinity clusters and translated into personas.',
          'This process surfaced recurring needs around controllable summaries, transparent feedback, and recovery from weak AI outputs.',
        ],
      },
      {
        header: 'Wireframes & Interactive Prototype',
        body: [
          'The design evolved from structure-first wireframes to interactive prototype states focused on summarization workflows.',
          'Interaction emphasis was placed on clarity, user control, and minimizing context switches while reading.',
        ],
      },
      {
        header: 'Evaluation & Analysis',
        bullets: [
          'Usability tests and heuristics identified gaps in error prevention, status visibility, and guidance.',
          'Regeneration needed more granularity so users could refine specific summary sections rather than entire outputs.',
          'Help and documentation had to be explicit for first-time feature discoverability.',
        ],
      },
      {
        header: 'Redesign Iterations',
        bullets: [
          'Added feedback collection before summary regeneration to steer AI output quality.',
          'Separated regeneration controls across summary sections for better user control.',
          'Introduced high-risk action warnings, clearer success/error states, and richer help documentation.',
        ],
      },
      {
        header: 'Outcome',
        body: [
          'Shaped an extension concept that demonstrates practical assistive reading support in everyday web experiences.',
        ],
      },
    ],
  },
  'magic-of-resilience': {
    subtitle: 'A non-fictional short documentary on Meta Illusions.',
    timeline: '2023',
    tools: 'Adobe Premiere Pro',
    focus: 'Videography',
    videoUrl: 'https://www.youtube.com/embed/n9K1AKpxHIA',
    heroImage: 'public/design-assets/project-media/magic-of-resilience/Screenshot_2025-01-24_at_15.47.19.png',
    gallery: ['public/design-assets/project-media/magic-of-resilience/Screenshot_2025-01-24_at_15.47.19.png'],
    sections: [
      {
        header: 'Project Overview',
        body: [
          'Magic of Resilience is a non-fiction short documentary centered on storytelling through grounded visual craft.',
        ],
      },
      {
        header: 'Role',
        body: [
          'As Director of Photography, I focused on visual language, shot planning, and continuity to support the documentary narrative.',
        ],
      },
      {
        header: 'Production Approach',
        bullets: [
          'Designed shot strategy to balance authenticity with visual coherence.',
          'Captured footage with attention to tone, pacing, and subject context.',
          'Collaborated through post-production to preserve narrative intent.',
        ],
      },
      {
        header: 'Outcome',
        body: [
          'Delivered a completed documentary piece showcasing local resilience through a cohesive visual narrative.',
        ],
      },
    ],
  },
  'lions-befrienders-communications-plan': {
    subtitle:
      'Integrated communications plan for Lions Befrienders (Singapore) — audiences, key messages, channel mix, and evaluation.',
    timeline: '2026',
    tools: 'Desk research, stakeholder mapping, messaging framework',
    gallery: [],
    sections: [
      {
        header: 'Project overview',
        body: [
          'A living workspace for the integrated communications plan (ICP). Use the standalone page for narrative and creative detail; this entry supports the portfolio shell when opened via project.html.',
        ],
      },
      {
        header: 'Plan structure',
        bullets: [
          'Situation & insight — context, gaps, and evidence.',
          'Goals & objectives — SMART goals by audience.',
          'Audience & positioning — segments, barriers, and proposition.',
          'Key messages & narrative — message house and proof points.',
          'Channel mix & tactics — owned, earned, and paid roadmap.',
          'Timeline, budget & measurement — KPIs and review cadence.',
        ],
      },
      {
        header: 'Next steps',
        body: [
          'Replace scaffold copy in the dedicated case study page with research, creative territories, and final approvals from Lions Befrienders stakeholders.',
        ],
      },
    ],
  },
};

