// Portfolio data modeled from exported Notion content.
window.PROJECTS = [
  {
    slug: 'pantry-pal',
    title: 'Pantry Pal',
    kind: 'uiux',
    kindLabel: 'ui/ux',
    year: '2024',
    role: 'UI Designer, UX Researcher',
    excerpt:
      'Mobile app concept tackling food waste by simplifying pantry management and meal planning.',
    tags: ['figma', 'foodtech', 'mobile'],
    href: 'case-studies/long-form.html',
    thumbLabel: 'pantry pal',
  },
  {
    slug: 'telegram-bot-heymax',
    title: 'Telegram Bot for Trip Planning | NUS Fintech Society × HeyMax',
    kind: 'code',
    kindLabel: 'code',
    year: '2025',
    role: 'Product Builder',
    excerpt:
      'Trip-planning Telegram bot project built for NUS Fintech Society in collaboration with HeyMax.',
    tags: ['telegram', 'automation', 'fintech'],
    href: 'case-studies/short-form.html',
    thumbLabel: 'telegram bot',
  },
  {
    slug: 'nusmart-dining-revamp',
    title: 'NUSMart Dining Revamp',
    kind: 'uiux',
    kindLabel: 'ui/ux',
    year: '2024',
    role: 'UI Designer, UX Researcher',
    excerpt: 'Revamped mobile app experience for NUSMart Dining.',
    tags: ['miro', 'mobile', 'service design'],
    href: 'case-studies/long-form.html',
  },
  {
    slug: 'flexijio',
    title: 'FlexiJio',
    kind: 'uiux',
    kindLabel: 'ui/ux',
    year: '2024',
    role: 'UX Researcher, UI Designer',
    excerpt: 'Desktop video conferencing platform for fitness classes and remote coaching.',
    tags: ['ux research', 'desktop', 'fitness'],
    href: 'case-studies/short-form.html',
  },
  {
    slug: 'fusion-scanner',
    title: 'Fusion Scanner',
    kind: 'uiux',
    kindLabel: 'ui/ux',
    year: '2023',
    role: 'UX Researcher, UI Designer',
    excerpt:
      'Browser extension concept to improve reading accessibility for language barriers and reading disabilities.',
    tags: ['balsamiq', 'figma', 'accessibility'],
    href: 'case-studies/long-form.html',
  },
  {
    slug: 'kita-communication-intervention',
    title: 'From Blind Box to Brochure, A Communication Intervention for Kita',
    kind: 'uiux',
    kindLabel: 'ui/ux',
    year: '2024',
    role: 'Designer',
    excerpt:
      'Communication intervention project focused on clarifying brand and messaging touchpoints for Kita.',
    tags: ['communication', 'intervention', 'branding'],
    href: 'case-studies/short-form.html',
  },
  {
    slug: 'brand-style-guide',
    title: 'Brand Style Guide',
    kind: 'uiux',
    kindLabel: 'graphic',
    year: '2023',
    role: 'Graphic Designer',
    excerpt: 'Comprehensive brand identity guideline built across print and digital assets.',
    tags: ['illustrator', 'indesign', 'photoshop'],
    href: 'case-studies/long-form.html',
  },
  {
    slug: 'miscellaneous-works',
    title: 'Miscellaneous Works',
    kind: 'uiux',
    kindLabel: 'graphic',
    year: '2023',
    role: 'Graphic Designer',
    excerpt: 'Curated selection of graphic design experiments and production-ready pieces.',
    tags: ['illustrator', 'indesign', 'graphic design'],
    href: 'case-studies/short-form.html',
  },
  {
    slug: 'magic-of-resilience',
    title: 'Magic of Resilience',
    kind: 'code',
    kindLabel: 'video',
    year: '2023',
    role: 'Director of Photography',
    excerpt: 'Non-fiction short documentary spotlighting local business Meta Illusions.',
    tags: ['videography', 'premiere pro', 'documentary'],
    href: 'case-studies/long-form.html',
  },
];

window.FEATURED = ['pantry-pal', 'telegram-bot-heymax', 'fusion-scanner'];
